/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/aboutpage/MainPage[0]': RouteRecordInfo<'/aboutpage/MainPage[0]', '/aboutpage/MainPage:0', { 0: ParamValue<true> }, { 0: ParamValue<false> }>,
    '/homepage/MainPage[0]': RouteRecordInfo<'/homepage/MainPage[0]', '/homepage/MainPage:0', { 0: ParamValue<true> }, { 0: ParamValue<false> }>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/useradmin/MainPage[0]': RouteRecordInfo<'/useradmin/MainPage[0]', '/useradmin/MainPage:0', { 0: ParamValue<true> }, { 0: ParamValue<false> }>,
  }
}
