/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    ExempleComponent: typeof import('./../components/ExempleComponent.vue')['default']
    GMainVideo: typeof import('./../components/g-appMain/GMainVideo.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    LoadingProgress: typeof import('./../components/g-progressBar/LoadingProgress.vue')['default']
    LoginComponent: typeof import('./../components/g-usersComponent/LoginComponent.vue')['default']
    LogoutComponent: typeof import('./../components/g-usersComponent/LogoutComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./../components/g-themeComponent/ThemeSwitcher.vue')['default']
    UsersComponent: typeof import('./../components/g-usersComponent/UsersComponent.vue')['default']
  }
}
